import type { Language } from "../i18n-context";

export const legalTranslations: Record<Language, Record<string, string>> = {
  en: {
    // Terms agreement checkbox
    "legal.agree_prefix": "I have read and agree to the ",
    "legal.terms_of_service": "Terms of Service",
    "legal.and": " and ",
    "legal.privacy_policy": "Privacy Policy",
    "legal.agreement_required": "Please read and agree to the Terms of Service and Privacy Policy",

    // Terms of Service page
    "legal.terms.title": "Terms of Service",
    "legal.terms.effective_date": "Effective Date: January 1, 2025",
    "legal.terms.welcome": "Welcome to AI Higress Gateway (hereinafter referred to as \"this Platform\" or \"we\"). By accessing or using this Platform, you agree to be bound by the following Terms of Service. If you do not agree to these terms, please do not use this Platform.",

    "legal.terms.section1.title": "1. Service Description",
    "legal.terms.section1.content": "This Platform provides AI model API aggregation gateway services, including but not limited to: multi-provider API routing, load balancing, usage statistics, and related technical services. We reserve the right to modify, suspend, or terminate any part of the services at any time without prior notice.",

    "legal.terms.section2.title": "2. User Eligibility",
    "legal.terms.section2.content": "You must be at least 18 years old or have reached the age of majority in your jurisdiction to use this Platform. By using this Platform, you represent and warrant that you meet these requirements.",

    "legal.terms.section3.title": "3. Acceptable Use Policy",
    "legal.terms.section3.intro": "You agree NOT to use this Platform for any of the following purposes:",
    "legal.terms.section3.item1": "Any activity that violates applicable laws, regulations, or legal requirements",
    "legal.terms.section3.item2": "Activities that endanger national security, leak state secrets, or subvert state power",
    "legal.terms.section3.item3": "Inciting ethnic hatred, ethnic discrimination, or undermining national unity",
    "legal.terms.section3.item4": "Spreading rumors, disturbing social order, or undermining social stability",
    "legal.terms.section3.item5": "Spreading obscenity, pornography, gambling, violence, terror, or criminal incitement",
    "legal.terms.section3.item6": "Insulting or defaming others, infringing on others' reputation, privacy, or other legitimate rights",
    "legal.terms.section3.item7": "Conducting fraud, phishing, or any form of illegal financial activities",
    "legal.terms.section3.item8": "Attacking, disrupting, or attempting unauthorized access to computer systems or networks",
    "legal.terms.section3.item9": "Generating, spreading, or storing content that infringes intellectual property rights",
    "legal.terms.section3.item10": "Any other activities prohibited by laws, regulations, or this Platform's policies",

    "legal.terms.section4.title": "4. User Responsibilities",
    "legal.terms.section4.content": "You are solely responsible for all activities conducted through your account. You agree to: (a) maintain the confidentiality of your account credentials; (b) promptly notify us of any unauthorized use; (c) ensure all content you generate or process complies with applicable laws and these terms.",

    "legal.terms.section5.title": "5. Intellectual Property",
    "legal.terms.section5.content": "All intellectual property rights in this Platform and its services belong to us or our licensors. You may not copy, modify, distribute, sell, or lease any part of our services or software without our explicit written permission.",

    "legal.terms.section6.title": "6. Disclaimer of Warranties",
    "legal.terms.section6.intro": "THIS PLATFORM IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\" WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:",
    "legal.terms.section6.item1": "Warranties of merchantability, fitness for a particular purpose, and non-infringement",
    "legal.terms.section6.item2": "Any warranty that the service will be uninterrupted, timely, secure, or error-free",
    "legal.terms.section6.item3": "Any warranty regarding the accuracy, reliability, or completeness of any content generated through AI models",
    "legal.terms.section6.item4": "Any warranty that defects will be corrected or that the platform is free of viruses or harmful components",
    "legal.terms.section6.item5": "Any warranty regarding the results obtained from using this platform or any third-party AI providers",

    "legal.terms.section7.title": "7. AI Content Disclaimer",
    "legal.terms.section7.intro": "You acknowledge and agree that:",
    "legal.terms.section7.item1": "Content generated by AI models may be inaccurate, incomplete, outdated, or misleading. You must independently verify any AI-generated content before relying on it for any purpose",
    "legal.terms.section7.item2": "We do not control, endorse, or assume responsibility for any content generated by third-party AI model providers accessed through this platform",
    "legal.terms.section7.item3": "AI-generated content should not be used as a substitute for professional advice (including but not limited to legal, medical, financial, or technical advice)",
    "legal.terms.section7.item4": "You are solely responsible for any decisions, actions, or consequences arising from your use of AI-generated content",
    "legal.terms.section7.item5": "We are not liable for any harm, loss, or damage resulting from AI-generated content, including content that may be offensive, harmful, or violate third-party rights",

    "legal.terms.section8.title": "8. Third-Party Services Disclaimer",
    "legal.terms.section8.content": "This platform aggregates services from multiple third-party AI providers. We are not responsible for: (a) the availability, quality, or performance of third-party services; (b) any changes, interruptions, or discontinuation of third-party services; (c) any data processed by third-party providers; (d) any terms, policies, or practices of third-party providers. Your use of third-party services is at your own risk and subject to their respective terms of service.",

    "legal.terms.section9.title": "9. Limitation of Liability",
    "legal.terms.section9.intro": "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:",
    "legal.terms.section9.item1": "We shall not be liable for any indirect, incidental, special, consequential, punitive, or exemplary damages, including but not limited to damages for loss of profits, goodwill, data, or other intangible losses",
    "legal.terms.section9.item2": "We shall not be liable for any damages arising from: (i) your use or inability to use this platform; (ii) unauthorized access to or alteration of your data; (iii) statements or conduct of any third party; (iv) any other matter relating to this platform",
    "legal.terms.section9.item3": "Our total aggregate liability for any claims arising from or related to these terms or your use of this platform shall not exceed the amount you paid to us (if any) in the twelve (12) months preceding the claim",
    "legal.terms.section9.item4": "Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability for certain damages. In such jurisdictions, our liability shall be limited to the maximum extent permitted by law",

    "legal.terms.section10.title": "10. Indemnification",
    "legal.terms.section10.content": "You agree to indemnify, defend, and hold harmless this platform, its operators, affiliates, officers, directors, employees, and agents from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from or related to: (a) your use of this platform; (b) your violation of these terms; (c) your violation of any rights of any third party; (d) any content you generate, submit, or process through this platform.",

    "legal.terms.section11.title": "11. Termination",
    "legal.terms.section11.content": "We reserve the right to suspend or terminate your access to this Platform at any time, with or without cause, and with or without notice. Upon termination, your right to use the Platform will immediately cease. All provisions of these terms that by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, indemnification, and limitations of liability.",

    "legal.terms.section12.title": "12. Governing Law",
    "legal.terms.section12.content": "These Terms shall be governed by and construed in accordance with the laws of the People's Republic of China. Any disputes arising from or relating to these terms shall be submitted to the competent court in the jurisdiction where this Platform is operated.",

    "legal.terms.section13.title": "13. Changes to Terms",
    "legal.terms.section13.content": "We reserve the right to modify these Terms at any time. Continued use of this Platform after any changes constitutes your acceptance of the new Terms.",

    "legal.terms.contact": "If you have any questions about these Terms, please contact us through the Platform's official channels.",

    // Privacy Policy page
    "legal.privacy.title": "Privacy Policy",
    "legal.privacy.effective_date": "Effective Date: January 1, 2025",
    "legal.privacy.intro": "This Privacy Policy explains how AI Higress Gateway collects, uses, and protects your personal information. By using this Platform, you consent to the practices described in this policy.",

    "legal.privacy.section1.title": "1. Information We Collect",
    "legal.privacy.section1.content": "We may collect: (a) Account information (email, username); (b) Usage data (API calls, request logs); (c) Technical data (IP address, browser type, device information); (d) Payment information (processed by third-party payment providers).",

    "legal.privacy.section2.title": "2. How We Use Your Information",
    "legal.privacy.section2.content": "We use your information to: (a) Provide and maintain our services; (b) Process your transactions; (c) Communicate with you about service updates; (d) Improve our services; (e) Comply with legal obligations.",

    "legal.privacy.section3.title": "3. Information Sharing",
    "legal.privacy.section3.content": "We do not sell your personal information. We may share information with: (a) Service providers who assist in our operations; (b) Legal authorities when required by law; (c) Third parties with your explicit consent.",

    "legal.privacy.section4.title": "4. Data Security",
    "legal.privacy.section4.content": "We implement appropriate technical and organizational measures to protect your personal information. However, no method of transmission over the Internet is 100% secure.",

    "legal.privacy.section5.title": "5. Your Rights",
    "legal.privacy.section5.content": "You have the right to: (a) Access your personal information; (b) Correct inaccurate data; (c) Request deletion of your data; (d) Withdraw consent for data processing.",

    "legal.privacy.section6.title": "6. Contact Us",
    "legal.privacy.section6.content": "If you have questions about this Privacy Policy, please contact us through the Platform's official channels.",
  },
  zh: {
    // Terms agreement checkbox
    "legal.agree_prefix": "我已阅读并同意",
    "legal.terms_of_service": "服务条款",
    "legal.and": "和",
    "legal.privacy_policy": "隐私政策",
    "legal.agreement_required": "请阅读并同意服务条款和隐私政策",

    // Terms of Service page
    "legal.terms.title": "服务条款",
    "legal.terms.effective_date": "生效日期：2025年1月1日",
    "legal.terms.welcome": "欢迎使用 AI Higress Gateway（以下简称「本平台」或「我们」）。访问或使用本平台即表示您同意受以下服务条款的约束。如果您不同意这些条款，请勿使用本平台。",

    "legal.terms.section1.title": "一、服务说明",
    "legal.terms.section1.content": "本平台提供 AI 模型 API 聚合网关服务，包括但不限于：多供应商 API 路由、负载均衡、使用统计及相关技术服务。我们保留随时修改、暂停或终止任何部分服务的权利，恕不另行通知。",

    "legal.terms.section2.title": "二、用户资格",
    "legal.terms.section2.content": "您必须年满18周岁或已达到您所在司法管辖区的法定成年年龄方可使用本平台。使用本平台即表示您声明并保证符合这些要求。",

    "legal.terms.section3.title": "三、禁止行为",
    "legal.terms.section3.intro": "您同意不得将本平台用于以下任何目的：",
    "legal.terms.section3.item1": "任何违反适用法律法规或法律要求的活动",
    "legal.terms.section3.item2": "危害国家安全、泄露国家秘密、颠覆国家政权的活动",
    "legal.terms.section3.item3": "煽动民族仇恨、民族歧视，破坏民族团结",
    "legal.terms.section3.item4": "散布谣言，扰乱社会秩序，破坏社会稳定",
    "legal.terms.section3.item5": "传播淫秽、色情、赌博、暴力、恐怖或教唆犯罪的内容",
    "legal.terms.section3.item6": "侮辱或诽谤他人，侵犯他人名誉、隐私或其他合法权益",
    "legal.terms.section3.item7": "进行诈骗、钓鱼或任何形式的非法金融活动",
    "legal.terms.section3.item8": "攻击、破坏或试图未经授权访问计算机系统或网络",
    "legal.terms.section3.item9": "生成、传播或存储侵犯知识产权的内容",
    "legal.terms.section3.item10": "法律法规或本平台政策禁止的任何其他活动",

    "legal.terms.section4.title": "四、用户责任",
    "legal.terms.section4.content": "您对通过您的账户进行的所有活动承担全部责任。您同意：（a）保守您的账户凭证的机密性；（b）及时通知我们任何未经授权的使用；（c）确保您生成或处理的所有内容符合适用法律和本条款。",

    "legal.terms.section5.title": "五、知识产权",
    "legal.terms.section5.content": "本平台及其服务的所有知识产权归我们或我们的许可方所有。未经我们明确书面许可，您不得复制、修改、分发、出售或出租我们服务或软件的任何部分。",

    "legal.terms.section6.title": "六、免责声明",
    "legal.terms.section6.intro": "本平台按「现状」和「可用」基础提供，不提供任何形式的明示或暗示保证。在法律允许的最大范围内，我们明确免除以下保证责任：",
    "legal.terms.section6.item1": "适销性、特定用途适用性和非侵权性的保证",
    "legal.terms.section6.item2": "服务将不间断、及时、安全或无错误的任何保证",
    "legal.terms.section6.item3": "通过 AI 模型生成的任何内容的准确性、可靠性或完整性的任何保证",
    "legal.terms.section6.item4": "缺陷将被修复或平台无病毒或有害组件的任何保证",
    "legal.terms.section6.item5": "使用本平台或任何第三方 AI 供应商所获得结果的任何保证",

    "legal.terms.section7.title": "七、AI 内容免责声明",
    "legal.terms.section7.intro": "您确认并同意：",
    "legal.terms.section7.item1": "AI 模型生成的内容可能不准确、不完整、过时或具有误导性。您必须在依赖任何 AI 生成的内容之前独立核实",
    "legal.terms.section7.item2": "我们不控制、不认可、也不对通过本平台访问的第三方 AI 模型供应商生成的任何内容承担责任",
    "legal.terms.section7.item3": "AI 生成的内容不应作为专业建议的替代品（包括但不限于法律、医疗、财务或技术建议）",
    "legal.terms.section7.item4": "您对使用 AI 生成内容所做出的任何决定、采取的任何行动或产生的任何后果承担全部责任",
    "legal.terms.section7.item5": "我们对 AI 生成内容造成的任何伤害、损失或损害不承担责任，包括可能具有冒犯性、有害或侵犯第三方权利的内容",

    "legal.terms.section8.title": "八、第三方服务免责声明",
    "legal.terms.section8.content": "本平台聚合来自多个第三方 AI 供应商的服务。我们不对以下情况负责：（a）第三方服务的可用性、质量或性能；（b）第三方服务的任何变更、中断或终止；（c）第三方供应商处理的任何数据；（d）第三方供应商的任何条款、政策或做法。您使用第三方服务的风险由您自行承担，并受其各自服务条款的约束。",

    "legal.terms.section9.title": "九、责任限制",
    "legal.terms.section9.intro": "在适用法律允许的最大范围内：",
    "legal.terms.section9.item1": "我们不对任何间接、附带、特殊、后果性、惩罚性或惩戒性损害承担责任，包括但不限于利润损失、商誉损失、数据损失或其他无形损失",
    "legal.terms.section9.item2": "我们不对以下情况造成的任何损害承担责任：（i）您使用或无法使用本平台；（ii）对您数据的未经授权访问或篡改；（iii）任何第三方的陈述或行为；（iv）与本平台相关的任何其他事项",
    "legal.terms.section9.item3": "对于因本条款或您使用本平台而产生的任何索赔，我们的总累计责任不超过您在索赔前十二（12）个月内向我们支付的金额（如有）",
    "legal.terms.section9.item4": "某些司法管辖区不允许排除某些保证或限制某些损害的责任。在此类司法管辖区，我们的责任将限于法律允许的最大范围",

    "legal.terms.section10.title": "十、赔偿",
    "legal.terms.section10.content": "您同意赔偿、辩护并使本平台、其运营商、关联公司、高管、董事、员工和代理人免受因以下情况引起或与之相关的任何和所有索赔、损害、损失、责任、成本和费用（包括合理的律师费）的损害：（a）您对本平台的使用；（b）您违反本条款；（c）您侵犯任何第三方的权利；（d）您通过本平台生成、提交或处理的任何内容。",

    "legal.terms.section11.title": "十一、终止",
    "legal.terms.section11.content": "我们保留随时暂停或终止您访问本平台的权利，无论有无原因，无论是否通知。终止后，您使用本平台的权利将立即停止。本条款中按其性质应在终止后继续有效的所有条款将继续有效，包括所有权条款、保证免责声明、赔偿和责任限制。",

    "legal.terms.section12.title": "十二、适用法律",
    "legal.terms.section12.content": "本条款受中华人民共和国法律管辖并按其解释。因本条款引起的或与之相关的任何争议应提交本平台运营所在地有管辖权的法院解决。",

    "legal.terms.section13.title": "十三、条款变更",
    "legal.terms.section13.content": "我们保留随时修改本条款的权利。在任何变更后继续使用本平台即表示您接受新的条款。",

    "legal.terms.contact": "如果您对本条款有任何疑问，请通过本平台的官方渠道与我们联系。",

    // Privacy Policy page
    "legal.privacy.title": "隐私政策",
    "legal.privacy.effective_date": "生效日期：2025年1月1日",
    "legal.privacy.intro": "本隐私政策说明 AI Higress Gateway 如何收集、使用和保护您的个人信息。使用本平台即表示您同意本政策中描述的做法。",

    "legal.privacy.section1.title": "一、我们收集的信息",
    "legal.privacy.section1.content": "我们可能收集：（a）账户信息（电子邮件、用户名）；（b）使用数据（API 调用、请求日志）；（c）技术数据（IP 地址、浏览器类型、设备信息）；（d）支付信息（由第三方支付服务商处理）。",

    "legal.privacy.section2.title": "二、我们如何使用您的信息",
    "legal.privacy.section2.content": "我们使用您的信息来：（a）提供和维护我们的服务；（b）处理您的交易；（c）就服务更新与您沟通；（d）改进我们的服务；（e）遵守法律义务。",

    "legal.privacy.section3.title": "三、信息共享",
    "legal.privacy.section3.content": "我们不会出售您的个人信息。我们可能与以下各方共享信息：（a）协助我们运营的服务提供商；（b）法律要求时的法律机关；（c）在您明确同意的情况下的第三方。",

    "legal.privacy.section4.title": "四、数据安全",
    "legal.privacy.section4.content": "我们采取适当的技术和组织措施来保护您的个人信息。但是，互联网上的传输方式都不是百分之百安全的。",

    "legal.privacy.section5.title": "五、您的权利",
    "legal.privacy.section5.content": "您有权：（a）访问您的个人信息；（b）更正不准确的数据；（c）请求删除您的数据；（d）撤回对数据处理的同意。",

    "legal.privacy.section6.title": "六、联系我们",
    "legal.privacy.section6.content": "如果您对本隐私政策有任何疑问，请通过本平台的官方渠道与我们联系。",
  },
};
